### ISSUE TITLE
Routing Error  No route matches {:action=>"show", :controller=>"rails_admin/main", :model_name=>"contact", :id=>"example@gmail.com"}

### ISSUE THREAD

**Issue by dvorab** [sferik/rails_admin#1690]
I Have Contact model with email address as the '_id' field ( I use mongoid db)
rails_admin does'nt allow me view contacts (I think it's the 'id' because the other models are fine)
this is the error:
Routing Error  No route matches {:action=>"show", :controller=>"rails_admin/main", :model_name=>"contact", :id=>"example@gmail.com"}
(the url => http://localhost:3000/admin/contact)

Can you help?
thanks

**Comment by clickripple** [comment]
i am not able to create route in rails getting following error.please help
  No route matches {:action=>"check_action", :controller=>"rails_admin/custom"}

**Comment by etagwerker** [comment]
I ran into this issue today.

This might be useful for people who run into this issue: https://github.com/sferik/rails_admin/wiki/Has-one-association

Also, you should check that model and try to find what's different between that model and the other models. 

In my case, I had some custom code that did this: 

```
  after_initialize do |user|
    user.build_user_info if user.user_info.blank?
  end
```

That code would build an associated `user_info` object with a `nil` id. That was confusing `rails_admin` who was expecting the object to have an ID in order to generate the show path. 

I hope it helps!
