### ISSUE TITLE
belongs_to association in new action will get errors when clicking on the input box or the arrow next to it.

### ISSUE THREAD

**Issue by pencilcheck** [sferik/rails_admin#2114]
```
NoMethodError - undefined method `associations' for nil:NilClass:
06:58:44 web.1     |    () Users/pencilcheck/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/rails_admin-fe356f30ebc3/lib/rails_admin/adapters/mongoid/abstract_object.rb:8:in `initialize'
06:58:44 web.1     |    () Users/pencilcheck/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/rails_admin-fe356f30ebc3/lib/rails_admin/adapters/mongoid.rb:18:in `get'
06:58:44 web.1     |    () Users/pencilcheck/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/rails_admin-fe356f30ebc3/app/controllers/rails_admin/main_controller.rb:136:in `get_association_scope_from_params'
06:58:44 web.1     |    () Users/pencilcheck/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/rails_admin-fe356f30ebc3/app/controllers/rails_admin/main_controller.rb:30:in `list_entries'
06:58:44 web.1     |    () Users/pencilcheck/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/rails_admin-fe356f30ebc3/lib/rails_admin/config/actions/index.rb:30:in `block (2 levels) in <class:Index>'
06:58:44 web.1     |   (eval):8:in `index'
```

What I observe the problem is that the new action still sends a source_object_id as part of the url param, the object id might be an temporary id generated from mongoid, the record doesn't exist therefore in mongoid.rb:18, model.find(id) returns nil.

And it shouldn't be happening because it is in the new action of course the id doesn't exist.

**Comment by rmachielse** [comment]
@pencilcheck did you find a solution for this problem?

**Comment by pencilcheck** [comment]
I don't think so.

**Comment by h8rry** [comment]
I am still seeing this problem. Using mongoid. But, when I start with a clean db with no data, this problem is gone.

Any ideas?

**Comment by h8rry** [comment]
@pencilcheck please see #2922 and try to reproduce it

**Comment by h8rry** [comment]
Solution is here hidden in docs: https://github.com/sferik/rails_admin/wiki/Associations-scoping

**Comment by mltsy** [comment]
It looks like the reason this only happens in production for many people is that by default, if there are less than 100 items in the associated collection, they are all cached on page-load, so there is no separate API call to fail.  This is the same issue: https://github.com/sferik/rails_admin/issues/2623

It's caused by MongoID being configured to not raise an exception (and instead, return nil) when the document is not found.  If you don't mind changing the config setting in mongoid.yml to `raise_not_found_error: true` - that would solve it.  However, this is definitely a bug that would be easy to fix (just check for nil before proceeding!)

**Comment by mltsy** [comment]
Actually though, that would just raise a more helpful exception, which would say the DocumentNotFound.  The REAL bug is, as @pencilcheck pointed out, the fact that rails_admin is passing a `source_object_id` to the API, when the source object has not been persisted.

**Comment by mltsy** [comment]
This is still a persistent and very annoying bug in our production environment (which uses MongoID).  It happens any time I try to select an associated "belongs_to" relation when creating a new record, and the associated collection options are plentiful enough to trigger loading via AJAX rather than embedding all options in the HTML.

**Comment by dfabreguette-ap** [comment]
I agree, it's very annoying to be forced to set "raise_not_found_error" config to true, even in development mode. Anyone has an idea to solve that ?

**Comment by mshibuya** [comment]
Merging this to #2623.
