### ISSUE TITLE
Error when use Rails 4.2

### ISSUE THREAD

**Issue by JohnBat26** [sferik/rails_admin#2145]
Hello.
I am trying migrate to Rails 4.2 and get next error when open rails_admin:

```
Showing /home/johnbat26/.rvm/gems/ruby-2.1.5@wc/bundler/gems/rails_admin-78d711046754/app/views/layouts/rails_admin/application.html.haml where line #8 raised:

"[class^="icon-"]" failed to @extend ".fa".
The selector ".fa" was not found.
Use "@extend .fa !optional" if the extend should be able to fail.
```

**Comment by Dinuz** [comment]
@fmh why I should precompile the assets?
I got a similar error, and after I followed you procedure, everything worked fine.

I then removed the assets folder from my public folder, in order to don't use more the asset precompiled, and everything still works fine

Why that? what assets:precompile does? keep in mind that I am in dev mode, and rails should't care about precompile except in production

**Comment by tobob** [comment]
I have this error when I tried to precompile assets under production

Rails 4.2.0 ruby 2.2.0

**Comment by RickCarlino** [comment]
Has anyone been able to work around this one in Heroku?

**Comment by mshibuya** [comment]
#2154 should have fixed this.
