### ISSUE TITLE
Rails Admin ui for devise login

### ISSUE THREAD

**Issue by vishalvijay** [sferik/rails_admin#2261]
Hi
I'm using rails_admin (0.6.7) with devise. Now I want to get the same Rails Admin UI for login page also. If it is possible, how do I do that?

**Comment by kpblc** [comment]
not sure what you want, but you can customise any devise page.  
rails generate devise:views
it will create views with all devise pages

**Comment by vishalvijay** [comment]
What I meant to tell is, active_admin has devise integration along with nice ui. Do rails_admin also have something similar (ui) or can I achieve it by rails_admin layout file ?

![screenshot from 2015-04-22 10 24 05](https://cloud.githubusercontent.com/assets/2828848/7267535/4e858ca0-e8da-11e4-8359-8ae757ea7c6b.png)

**Comment by kpblc** [comment]
ok i understand now, but i think there is no auto generated layout with rails_admin styles.
but as i said before, you can manually run "rails generate devise:views"
then go to "app / views / devise / registrations " and redact page as you want.

**Comment by vishalvijay** [comment]
Ya I got it. Thanks

**Comment by Prashanth-M** [comment]
@vishalvijay  Have you found the solution for UI of login page?

**Comment by vishalvijay** [comment]
@Prashanth-M I didn't found, I had to manally style devise login page

**Comment by Prashanth-M** [comment]
Thanks!. Then I will do the same way.

**Comment by jigarius** [comment]
I think it might be a good idea to bake in login/logout page features. The reason I think so is because many Rails apps these days have Rails Admin just for administration. The frontend is probably a React or Angular app. So, currently, if I build my entire Rails admin with Rails Admin, I still have to do some extra work to make the login page match the Rails Admin appearance.

What I'll try next is to see if there's an easy way to include the entire Rails Admin layout/styling on devise's login/logout views.
