### ISSUE TITLE
What has happened to the DSL documentation?

### ISSUE THREAD

**Issue by benshimmin** [sferik/rails_admin#2357]
It used to look like this: https://github.com/sferik/rails_admin/wiki/Railsadmin-DSL/b583fe09e9f9278711a262cec06665d2108372c8

Now it looks like this: https://github.com/sferik/rails_admin/wiki/Railsadmin-DSL

Has it moved somewhere else?

**Comment by rikkipitt** [comment]
Looks like someone overwrote it here: https://github.com/sferik/rails_admin/wiki/Railsadmin-DSL/_history (Jun 3). demoabc - looks like a spam user!

No wonder I couldn't find any reference to ```object_label_method``` when I was looking for it recently!

**Comment by mshibuya** [comment]
Now it has been decomposed to several pages, because it's too bloated.
https://github.com/sferik/rails_admin/wiki/Models
https://github.com/sferik/rails_admin/wiki/Groups
https://github.com/sferik/rails_admin/wiki/Fields

Anyway, I'm wondering why do people stick to that old https://github.com/sferik/rails_admin/wiki/Railsadmin-DSL page? Is there any link pointing to it?
I've destroyed the page a couple of times, and found somebody re-creating it.

@rikkipitt It has been moved to Models page, since it's a model-based configuration:
https://github.com/sferik/rails_admin/wiki/Models#the-object_label_method-method

**Comment by mshibuya** [comment]
@andruby I've marked Railsadmin-DSL page as obsolete, so please never roll it back :worried:

**Comment by andruby** [comment]
@mshibuya. My bad, I hadn't seen this issue and assumed a bot deleted the page. 

The project's readme file links to this page, which is why I was confused that it only shows a tiny ruby example. Maybe we can link to the 3 replacement pages for people like me who still remember getting most information from that page :)

**Comment by mshibuya** [comment]
Oh sorry, I didn't notice that link :astonished: 
Fixed now, thanks for advice!
