### ISSUE TITLE
ArgumentError for Japanese Dates

### ISSUE THREAD

**Issue by vleango** [sferik/rails_admin#2454]
My app is set to use Japanese (:ja) locale.

When I try to update a record, I get an argument out of range error from time_zone.rb
I believe the error is with records with datetime fields. My table has a current_sign_in_at column, and the date is displayed like this in admin_rails: 2015年11月04日(水)

**Comment by zcpdog** [comment]
seem issue here.

**Comment by bbenezech** [comment]
Can you provide a failing test?
That would help a lot to provide a fix.

**Comment by mreinsch** [comment]
we were just hit by that as well; I'm also expecting that everyone using RailsAdmin in a non-English locale has a potential problem, as the date / time is rendered according to the locale settings which can't necessarily be parsed back into a correct date.

The behavior is quite bad, btw. We just noticed strange issues for some users. Turns out some important datetime fields where quietly reset by just saving the record through RailsAdmin.

**Comment by mshibuya** [comment]
Closed by https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a .
