### ISSUE TITLE
active_record-acts_as gem compatability

### ISSUE THREAD

**Issue by hut8** [sferik/rails_admin#2463]
I'm a bit lost about how to make this work with the [active_record-acts_as](https://github.com/hzamani/active_record-acts_as) gem. Basically, that gem implements multiple table inheritance (aka class table inheritance).

Let's say you have a `Product` base class, and then a `Widget` and a `Foo` class where each of these  `acts_as :product`. Product has a polymorphic `has_one` relationship with `Widget` and `Foo` -- in the `Product` table, there's an `actable_type` and `actable_id` column, along with its own `id`.

If I go into the Rails console and simply do `Widget.create!`, two rows are inserted, and everyone is happy. But with `rails_admin`, no such luck. There are no fields to hide on the `Widget` model since the polymorphism is on the other end (that was my first and only idea of a workaround). Any ideas?

**Comment by wongwf82** [comment]
What if you were to user Concerns for your models instead of using inheritance?

https://gist.github.com/dhh/1014971

So for example your Product could 'include Widgetible' which will separate out anything concerning widget. On the database table level though, there will be mixing up of values in the same table.

That is one idea that I can think of which will keep Product editable.

**Comment by bbenezech** [comment]
`Simulates multiple-table-inheritance (MTI) for ActiveRecord models.` :goberserk:  
STI is already problematic enough, I humbly suggest anyone abstains from using this kind of pattern, for their own sanity.
