### ISSUE TITLE
Time field parse error

### ISSUE THREAD

**Issue by TangMonk** [sferik/rails_admin#2549]
I have a model with postgresql `time` fields, 

```
create_table "maxi_times", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.time     "time"
  end
```

If I create a record from rails_admin ui, it will shows unexcept value, like follow step:

![](http://i.imgur.com/DFlfgGe.gif) (sorry for the unpaid screen record software for logo)

But I check my database, this column was correct with my input

**Comment by TangMonk** [comment]
Now I override `RailsAdmin::Config::Fields::Types::Time` class to fix that:

```
class RailsAdmin::Config::Fields::Types::Time
  def parse_value(value)
    Time.parse(value)
  end
end
```

**Comment by bbenezech** [comment]
What timezone is it showing in?
```ruby
>> Rails.application.config.time_zone
```

You can change it in `application.rb`:

```ruby
config.time_zone = ...
```

Let me now if it helps.

**Comment by TangMonk** [comment]
I am in china
```
pry(main)> Rails.application.config.time_zone
=> "Asia/Chongqing"
```

**Comment by bbenezech** [comment]
I have never used the time column. If it has no date associated, then it has no absolute value and should not be impacted by time zones.

When is the problem happening ? After or before being written to pg ?
Your opening post is confusing: you say that changing parse_value fixes the problem but that the value in the DB is good anyway. 

But parse_value happens before the DB write, so this makes no sense to me.

**Comment by fahmiardhianto** [comment]
Okay, I want to help re phrase the issue. Hopefully there will be a fix for this.

I got problem when trying to update `time` attribute. In the list or edit view, the value shown is time with timezone. But when I am trying to update the value, the value shown after the update will different from the value which I input.

For example, I want to update the time to 07:00. FYI, my app use +08:00 timezone. After I save, the value will become 15:00, instead of 07:00. When saving the value, rails admin did not take into account the timezone, which is weird for me because it calculate the timezone when showing. Overriding the parse_value method help me solve this issue.

**Comment by goofansu** [comment]
@TangMonk You should use `Time.zone.parse(value)` because `Time.parse` uses the system timezone. See https://thoughtbot.com/blog/its-about-time-zones

**Comment by mshibuya** [comment]
Closed by https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a .
