### ISSUE TITLE
How important is it to keep rails_admin under https?

### ISSUE THREAD

**Issue by ingolfured** [sferik/rails_admin#2655]
From security point of view, how important is it to keep rails_admin under https? Thanks!

**Comment by voyera** [comment]
That's a pretty broad question! I'm hoping my answer will help you :)

From a security perspective overall HTTPS is always better than HTTP simply because it adds extra layer of security on your website. Here's a brief summary of what it can do:

- You ensure that the website is the one the server it is supposed to be talking to. 
- It prevents being tempered by third parties.
- It encrypts all communications, including URLs, which protects things like browsing history and credit card numbers.
- It makes your site more secure for visitors.

If you're asking explicitly for Rails_Admin, I would say the strong advantage reside in the first 3 bullets in addition to whatever authentication gem you use (i.e: Devise). I personally think it's a strong approach to secure your website overall.

Is it super important? Not necessarily depending on what type of information you store, but I strongly suggest you invest the effort into deploying some sort of HTTPS/TLS solution when deploying your application, it's honestly not that hard especially with Let's Encrypt who offers free certificates and it even slightly help your google ranking so there's that :)

**Comment by mshibuya** [comment]
Thanks for the answer.
