### ISSUE TITLE
arabic datepicker not working

### ISSUE THREAD

**Issue by Fattouh92** [sferik/rails_admin#2777]
setting locale to :ar and using the datepicker results in:
- showing assyrian calendar that is not used anymore in arabic language as mentioned in this PR #2595 
- date is not being set

what i tried so far:
- destroying datepicker object and reinitializing with datepicker locale to en also doesn't set date
- change rails locale to :en and datepicker works normally

**Comment by btazi** [comment]
I have the same problem for the french language, have you found a solution ?

**Comment by Preen** [comment]
+1

**Comment by cec** [comment]
Using italian locale.
Selected date is displayed properly formatted, but the input field's value is not actually set.

**Comment by cec** [comment]
I'm hunting down the problem through a dummy app.
I managed to have the picker's value be set on the input.
Still, when editing a record, the value of the input is not shown until the picker is activated once.

The problem seems to stem from how you include your own locale in your app: 
- I wasn't using [rails-i18n](https://github.com/svenfuchs/rails-i18n) gem and added locales manually on my own (app is 5 years old atm)
- Removing my locale files and adding the gem got me a good way forward

**Comment by mshibuya** [comment]
Closed by https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a .
