### ISSUE TITLE
config.parent_controller setting does not work

### ISSUE THREAD

**Issue by grillermo** [sferik/rails_admin#2790]
On my project the config/initializers/rails_admin.rb file added 

    config.parent_controller = '::MyBaseController'

And rails admin ignores it, if i change directly the lib/rails_admin/config.rb file and hardcode this

    @parent_controller = '::MyBaseController

It works, my conclusion is that this mechanism 

    class ApplicationController < Config.parent_controller.constantize

Doesnt work.
I tested it using a before_action filter and i could confirm that doing

    self.class.superclass

Does not return the right class when using the config approach.

**Comment by tamaloa** [comment]
Had a similar problem when trying to set `config.parent_controller = '::ApplicationController'` to keep the old behaviour.
Could fix it by moving the config.parent_controller setting above my `config.audit_with` call. Try moving it to the very beginning of the config block. I guess some config calls instantiate the controller so that the setting later takes no effect anymore.

**Comment by grillermo** [comment]
Will try that, thank you
