### ISSUE TITLE
Problem in multiple select save method

### ISSUE THREAD

**Issue by gregorybruneau** [sferik/rails_admin#2912]
Hello all,

We are experiencing an issue with the multiple select :
Considering you have 10 items (from 1 to 10) that we can associate.
If you associating items number 1,2 and 3 and save, items are correctly saved.
But, if you edit it again, remove item number 3 and add it again and save : item number 3 will NOT be keep in the association. 

It is the same if you use « clear all » and add a previously associated item and save : it will be NOT kept.

Is anyone have the same problem ? Any solution/fix ?

Many thanks for your help ! 

Greg

**Comment by colinux** [comment]
Hi,

we are experiencing the same, with `rails_admin 0.8`, and after `1.2` upgrade. I failed to understand what's really going on. Firefox seems to have this issue more often than other browsers.

It's really strange because the web developer console shows that the dom is well updated when clicking on select/deselect, with the expected options selected. However the params received by Rails does not contain theses values !

My case concerns a relation configured like this :

```ruby
fields :facilities do
    associated_collection_cache_all true
    associated_collection_scope do
        hotel = bindings[:object]
        Proc.new { |scope|
           scope = scope.where(:site_id => hotel.site_id) if hotel.present?
        }
    end
end
```

**Comment by austinbachman** [comment]
Just want to chime in, I have experienced the same issue on `rails_admin 1.1.1`
