### ISSUE TITLE
Support for rails active storage

### ISSUE THREAD

**Issue by rgbskills** [sferik/rails_admin#2990]
Hey, are there any plans to support rails active storage? I have some implementation but other than uploading images to products I cant edit, view or delete images :(

**Comment by vitalyliber** [comment]
I need support for active storage also 🍰

**Comment by helphop** [comment]
I need it too :)

**Comment by Drowze** [comment]
I would love to see it live!

**Comment by dtcristo** [comment]
I've built an implementation of Active Storage support. I'm still working on the test suite before I create a PR. Despite this, it works great for uploading, viewing and deleting attachments. I haven't yet built support for `has_many_attached`.

It's available in the `active_storage` branch of my [fork](https://github.com/dtcristo/rails_admin/tree/active_storage).

Example usage:
```ruby
class User < ApplicationRecord
  has_one_attached :avatar

  # The following is needed to support deletion
  attr_accessor :remove_avatar
  after_save -> { avatar.purge }, if: -> { remove_avatar == '1' }

  rails_admin do
    field :avatar, :active_storage
  end
end

**Comment by helphop** [comment]
I will try it out tomorrow.

Thank you very much for creating the support, it is very much needed in my
current app.

-Mitchell

Mitch

**Comment by xire28** [comment]
Thank you !

Because active_storage is rails 5 only, I suggest using the attribute api for the documentation:

````ruby
class User < ApplicationRecord
  has_one_attached :avatar

  # The following is needed to support deletion
  attribute :remove_avatar, :boolean
  after_save ->{avatar.purge}, if: :remove_avatar

  rails_admin do
    field :avatar, :active_storage
  end
end
````

**Comment by dtcristo** [comment]
Thanks @xire28. That's an improvement.

**Comment by skryking** [comment]
Any chance there's been more done on this?

**Comment by scalderdom** [comment]
@skryking 
I implemented ActiveStorageMany field, but the UI is bad in some places. https://github.com/scalderdom/rails_admin/tree/active_storage

**Comment by scalderdom** [comment]
#3036

**Comment by marcelino056** [comment]
@dtcristo Did you have any update for many attached files?

**Comment by dtcristo** [comment]
Hi @marcelino056, I never implemented anything for `has_many_attached`, but @scalderdom has something working for this, see above.

**Comment by mshibuya** [comment]
I'm also working on support for that, and hopefully can be pushed soon.

**Comment by gutioliveira** [comment]
Hi @mshibuya, 

Using has_many_attached :images is throwing this error when editing the model:

```
Showing /Users/gustavo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rails_admin-1.4.1/app/views/rails_admin/main/_form_multiple_file_upload.html.haml where line #9 raised:

undefined method `' for #<Item:0x007fd797099950>

Around line #430:
      else
        match = matched_attribute_method(method.to_s)
        match ? attribute_missing(match, *args, &block) : super
      end
    end
```

**Comment by vsai** [comment]
^ I'm getting the same error when using `has_many_attached :images`

When I excluded the field `images`, the edit page loads fine.
Rails_admin works fine for `has_one_attached`.

**Comment by unRARed** [comment]
It appears to throw because the view assumes there is a `delete_method` per https://github.com/sferik/rails_admin/wiki/ActiveStorage#user-content-deleting-attachment.

After adding the virtual attribute(s) and `after_save` hooks, I now run into:

<img width="717" alt="screen shot 2018-11-04 at 10 35 50 pm" src="https://user-images.githubusercontent.com/1447940/47981799-1b1c2600-e082-11e8-97bf-a40e0841ce68.png">

**Comment by lengyelg** [comment]
People struggling with attachments not getting deleted even though you did everything above: it might be because of CSP (content security policy). Currently the delete button uses inline Javascript and that makes CSP incompatible unfortunately. You can disable it by adding `:unsafe_inline` on the `default_src` row in `config/initializers/content_securitypolicy.rb`, but pleaqse be aware of the security risk this poses to the application.

**Comment by erniux** [comment]
I do not know if this issue is still open, but I did this: Updated file _form_multiple_file_upload.html.haml last version and it works:

`- field.attachments.each_with_index do |attachment, i|
  .toggle 
    = attachment.pretty_value
    - if field.delete_method  
      %a.btn.btn-info.btn-remove-image{href: '#', :'data-toggle' => 'button', role: 'button',  onclick: "$(this).siblings('[type=checkbox]').click(); $(this).parent('.toggle').toggle('slow'); jQuery(this).toggleClass('btn-danger btn-info'); return false;"}
        %i.icon-white.icon-trash
        = I18n.t('admin.actions.delete.menu').capitalize + " #{field.label.downcase} ##{i + 1}"
      - if field.delete_method
        = form.check_box(field.delete_method, {multiple:true, style: 'display:none;'}, attachment.delete_value, nil)

= form.file_field(field.name, field.html_attributes.reverse_merge({ data: { :"multiple-fileupload" => true }, multiple: true }))

- if field.cache_method
  = form.hidden_field(field.cache_method)`
