### ISSUE TITLE
config/initializers/rails_admin.rb:4:in `block in <main>': undefined method `horizontal_scroll_list=' for RailsAdmin::Config:Module (NoMethodError)

### ISSUE THREAD

**Issue by syit** [sferik/rails_admin#3032]
I tried [this](https://github.com/sferik/rails_admin/wiki/Horizontally-scrolling-table-with-frozen-columns-in-list-view)  to make the list view table show all of the columns on a single page, with horizontal scrolling and frozen header columns in the table.

```
RailsAdmin.config do |config|
  ...
  # Use default horizontal scroll settings of 3 frozen columns (checkboxes, links/actions, ID) with a border on the right:
  config.horizontal_scroll_list = true

  # Use horizontal scrolling, but without any frozen columns:
  config.horizontal_scroll_list = {num_frozen_columns: 0}

```

But getting error 
`/config/initializers/rails_admin.rb:4:in `block in <main>': undefined method `horizontal_scroll_list=' for RailsAdmin::Config:Module (NoMethodError)`

  rails_admin (1.3.0)

**Comment by mltsy** [comment]
I'm also not able to use horizontal_scroll_list in 1.4.1 ...

**Comment by mltsy** [comment]
Good point - sorry, apparently I didn't read [the documentation](https://github.com/sferik/rails_admin/wiki/Horizontally-scrolling-table-with-frozen-columns-in-list-view) closely enough!  I didn't realize it wasn't a merged feature yet.

I was also having trouble getting `total_columns_width` to do anything, which is why I quickly tried `horizontal_scroll_list` when I saw it was an option.  But I guess total_columns_width is unrelated to this issue, so I'll create a new one for that if I try again and still can't get it to work (I just have a bunch of checkbox fields that should really fit on one screen, but I can't get them to all show up)

**Comment by patleb** [comment]
You will have to play with `column_width` also, since its default is 120px. So if you have 10 columns, than you need `total_columns_width` at 1200px.

**Comment by mltsy** [comment]
Hey, I figured it out!  (I think I was actually just setting it in the wrong place - or a couple of wrong places, actually) 😄 Thanks!

**Comment by patleb** [comment]
:+1:

**Comment by waheedi** [comment]
What do we need to make progress on this, a pull request has been ready to migrate for a while already, Can we help?

**Comment by mshibuya** [comment]
#3017 is in the master now.
